/*
 * This file is generated by jOOQ.
 */
package com.infiniteautomation.mango.graphView.model;


import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GraphViewRecord extends TableRecordImpl<GraphViewRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>graphView.id</code>.
     */
    public GraphViewRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>graphView.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>graphView.xid</code>.
     */
    public GraphViewRecord setXid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>graphView.xid</code>.
     */
    public String getXid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>graphView.name</code>.
     */
    public GraphViewRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>graphView.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>graphView.context</code>.
     */
    public GraphViewRecord setContext(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>graphView.context</code>.
     */
    public String getContext() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return GraphView.GRAPH_VIEW.id;
    }

    @Override
    public Field<String> field2() {
        return GraphView.GRAPH_VIEW.xid;
    }

    @Override
    public Field<String> field3() {
        return GraphView.GRAPH_VIEW.name;
    }

    @Override
    public Field<String> field4() {
        return GraphView.GRAPH_VIEW.context;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getXid();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getContext();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getXid();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getContext();
    }

    @Override
    public GraphViewRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GraphViewRecord value2(String value) {
        setXid(value);
        return this;
    }

    @Override
    public GraphViewRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public GraphViewRecord value4(String value) {
        setContext(value);
        return this;
    }

    @Override
    public GraphViewRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GraphViewRecord
     */
    public GraphViewRecord() {
        super(GraphView.GRAPH_VIEW);
    }

    /**
     * Create a detached, initialised GraphViewRecord
     */
    public GraphViewRecord(Integer id, String xid, String name, String context) {
        super(GraphView.GRAPH_VIEW);

        setId(id);
        setXid(xid);
        setName(name);
        setContext(context);
    }
}
